[package]
name = "verwalter"
description = """
    Decentralized resource and configuration management daemon
"""
readme = "README.rst"
keywords = ["cluster", "linux", "resource", "configuration", "management"]
version = "0.2.0"
homepage = "http://github.com/tailhook/verwalter"
documentation = "http://verwalter.readthedocs.org"
authors = ["Paul Colomiets <paul@colomiets.name>"]

[dependencies]
rotor = "0.6.3"
rotor-http = "0.7.0"
rotor-tools = "0.3.2"
rotor-cantal = { rev="080ffac", git="git://github.com/tailhook/rotor-cantal" }
lua = { rev="9d3c7dc", git = "git://github.com/jcmoyer/rust-lua53" }
quick-error = "0.2.1"
liquid = "0.2"
argparse = "0.2"
handlebars = "0.15"
log = "0.3.2"
env_logger = "0.3.1"
tempfile = "1.1.1"
rustc-serialize = "0.3.16"
quire = "0.1.7"
yaml-rust = "0.3"
scan_dir = "0.3"
time = "0.1.32"
rand = "0.3.11"
libc = "0.2"
matches = "0.1.2"
hyper = "0.7"
mio = "0.5"
nix = "0.5.0"
cbor-codec = "0.5.0"
regex = "0.1.58"
lazy_static = "0.1.15"
sha1 = "0.1.1"
inotify = "0.2.3"
itertools = "0.4.15"

[dependencies.indexed_log]
path = "./indexed_log"

[[bin]]
name = "verwalter"
path = "src/daemon/main.rs"

[[bin]]
name = "verwalter_render"
path = "src/render/main.rs"
